### PR TITLE
Add test case query and test case selector along with a reload button

### PR DESCRIPTION
**Pull request by mikepoz59**
Add ability to retrieve test case queries and then execute those queries
to get the actual test case list.
Added a "reload" button that throws away any changes and reloads the
steps from the originally retrieved test case data.

I think I got it right, figured out what I did wrong last night and reverted that.  Hope this meets your expectations.

### CODE REVIEW

**Comment by ajryan** [comment]
This is starting to look really nice!

Taking a spin through the code, I see just a few things still to resolve:
1. MainForm should not need the _testCaseNumber member. Instead, GetTestCaseData should take an integer instead of the bool. In the Load click handler, parse the textbox and then call GetTestCaseData with the int. In the event handler from the query picker, just pass in the selected Id.
2. Let's make the query picker a true child window (or pallete window would be even better). It shouldn't show up as a separate top-level window for Alt+Tab, and it should always appear above the main window, even when the main window is maxmized. Also I can hit Alt+F4 on the picker, then next click on Select Query causes a crash.
3. Please include the Close (X) button on the upper-right of the query picker.
4. There is some dead code to delete in the Query/Test picker.
5. I think you can move the invoke check to PopulateTestList instead of on the inner AddToTestCaseList.
6. Anchoring is messed up on the buttons at the bottom of the picker. And need to set min width / height on the picker.
7. Certain queries are giving the message "You have specified a query string that is not valid when you use the query method for a flat list of work items".  I think this is due to using GetEnumerator/MoveNext. May need to either exclude nested queries OR come up with another way of traversing the query result and adding only test cases to the list.
8. I think we should skip the Refresh button. The way it's implemented I think there will be issues with the Results functionality. Let's focus on the query picker for this round, then we can look at Refresh in depth if you like. This also means that the refactor of the logic for DiscardCurrentChanges can go back the way it was.

You don't need to close this pull request to submit fixes -- just make the changes in your local repo, commit, and push them. Then you can add the new commit to this existing pull request -- there should be UI for that in your view of the pull request.

Thanks!

**Comment by mikepoz59** [comment]
-> This is starting to look really nice!

Thanks!

-> Taking a spin through the code, I see just a few things still to resolve:

-> MainForm should not need the _testCaseNumber member. Instead, GetTestCaseData should take an integer instead of the bool. In the Load click handler, parse the textbox and then call GetTestCaseData with the int. In the event handler from the query picker, just pass in the selected Id.

```
Done
```

-> Let's make the query picker a true child window (or pallete window would be even better). It shouldn't show up as a separate top-level window for Alt+Tab, and it should always appear above the main window, even when the main window is maxmized. 

```
Done (I think.  I set the Owner value to be the main editor window and this seems to give the functionality I believe you were you were seeking.)
```

-> Also I can hit Alt+F4 on the picker, then next click on Select Query causes a crash.

```
Added an “on closing” event handler to the picker that cancels the Close() and instead just hides the dialog instead of disposing it as part of the Close().  Had to add a "cancel = false" to the editor on_closing handler so the form could close (setting it on the query made it apply to the parent as well).
```

-> Please include the Close (X) button on the upper-right of the query picker.

```
Done.  See above for the handler.
```

-> There is some dead code to delete in the Query/Test picker.

```
Done
```

-> I think you can move the invoke check to PopulateTestList instead of on the inner AddToTestCaseList.

```
Done.
```

-> Anchoring is messed up on the buttons at the bottom of the picker. And need to set min width / height on the picker.

```
Done.  I thought I had gotten all the anchoring stuff done.  Set min height/width for the picker.
```

-> Certain queries are giving the message "You have specified a query string that is not valid when you use the query method for a flat list of work items". I think this is due to using GetEnumerator/MoveNext. May need to either exclude nested queries OR come up with another way of traversing the query result and adding only test cases to the list.

```
Done.  I went with excluding anything other than queries which return a flat list with test cases.
```

-> I think we should skip the Refresh button. The way it's implemented I think there will be issues with the Results functionality. Let's focus on the query picker for this round, then we can look at Refresh in depth if you like. This also means that the refactor of the logic for DiscardCurrentChanges can go back the way it was.

```
Done
```

-> You don't need to close this pull request to submit fixes -- just make the changes in your local repo, commit, and push them. Then you can add the new commit to this existing pull request -- there should be UI for that in your view of the pull request.

```
Roger that!  Update will be posted later today.
```

Thanks!
Mike

**Comment by mikepoz59** [comment]
Just realized I forgot to delete some commented out lines (used it to find where string _testCaseNumber was used).  Updating and will sync new changes.  sorry!

**Comment by ajryan** [comment]
Sorry for the delay, I hope to review and pull this tomorrow. For the CodePlex binary release, I really need to investigate TFS2012 compat issues, and would like to do a combo release with your new feature and the compat issues resolved.

**Comment by mikepoz59** [comment]
Not a problem. Thanks for letting me know.

I was thinking about seeing if the TFS DLLs will let me access MTM created "test pass" data sets, and if it does, see if I can add that functionality as well.  It was just a thought I had that I wanted to follow up on and then run by you if it is possible.

**Comment by ajryan** [comment]
Sorry bud - one more issue! On first run when no TFS project is connected, crash on a null ref exception if you click Select Query.

Also - what do you mean "access test pass data sets?" What is the use case exactly?

Thanks,
Aidan

**Comment by mikepoz59** [comment]
--> On first run when no TFS project is connected, crash on a null ref exception if you click Select Query.

Fixed, added a null check as well as fixed the "connection status" in the bottom status bar where after failure, it still says "Connecting..."

--> Also - what do you mean "access test pass data sets?" What is the use case exactly?

I was curious if there was support in Team Foundation Server that would let me actually access existing Test Pass collections as defined in MTM in addition to TFS created queries.  Unfortunately I've been a bit busy at work along with doing some home remodeling so I haven't had time to investigate it yet.  I'll leave that for another day, when things have slowed down.

Thanks!
Mike

**Comment by ajryan** [comment]
Thanks very much for this!

**Pull request merged**
