### PR TITLE
Update to support TFS test case query files

### PR DESCRIPTION
**Pull request by mikepoz59**
Added support to retrieve personal and team TFS queries and filter them
to make queries that contain "Test case" and "Test Case Category"
options.

To support this I added a Select Query button that opens a dialog that
displays the available queries in one of two formats, a tree view
(similar to what TFS offers) and a flat list.  The user can switch
between the two by selecting a radio button.

Once a query is selected, it's executed and a new window opens that
lists the test cases from the query.  Clicking on a test case entry in
the window will cause the Test Steps Editor to automatically load the
test cases.

Finally, I added a "Refresh" button that will get the test case ID of
the currently selected test case in the editor, close the tab and
re-retrieve the test case steps from the server.

### CODE REVIEW

**Comment by ajryan** [comment]
Hi Mike,

Thank you for taking the time to submit this. I took a quick look around. Can you please try to resolve the following? You can make your changes locally, commit, push, and then amed your pull request adding the new commit. 
1. C# code in this project has hard tabs, not spaces. Please use tabs, especially where you have modified existing files. In your current commit, the diff on mainform looks like the whole file changed because tabs are changed to spaces
2. The refresh button is a cool idea! But, closing and then re-opening the tab is not very efficient. It should be accomplished by a) confirming with the user if the test case is dirty and then b) clearing and re-loading the test within the current tab. This will eliminate the TestCaseNumber property from the main form, which does not smell too good. The icons for this project are from here: http://www.famfamfam.com/lab/icons/silk/  Please find a good one for the refresh button. Alternatively, you could pull that button back out and just focus on the query runner for now.
3. Should not manually set the location of querypicker or testcasepicker, good chance of them appearing offscreen, or in strange positions when using multiple monitors.
4. Name of Query Picker class and file should be QueryPicker, not SelectQuery -- class names should be nouns, not verbs. Likewise for Test Case Picker.
5. The UI is to "popup heavy" as it is -- I think the best thing would be to merge the query and test case pickers into a single window. I also don't think there's a need for the "flat" query list - just tree view is great. I would start with the tree expanded. When I have the editor window maximized, the interaction is not good, picker keeps getting pushed behind. It would be better to have the picker live in an expandable pane like results mode, but maybe from the left-hand side. I would be OK with the picker living in a floating pallette that always stays on top of the main window though.
6. Null ref exception if someone clicks "run query" with nothing selected.
7. Def don't pass an instance of mainform into the picker and let it set things back into mainform - that is a circular dependency and ripe for race conditions and hangs. And the method of putting the test case ID in the combo and then loading is way hacky. If you merge the two pickers, it should be simple for the picker to expose an event "TestCaseSelected" that the main form listens to.
8. Loading a test case should be triggered buy double-click or button press, not single select. Too easy to accidentally open one.
9. There is definitely a concurrency problem with the test case picker (I got an email from my bug reporter from a crash that I assume happened while you were testing) -- having a warning "wait for one to finish before clicking another" is not acceptable, this tool needs to be as rock solid as possible. Moving to the event model should allow the mainform to control whether it responds to a select event from the picker depending if it's already busy loading a case.

Thanks again! I think this can turn out to be really useful.

Aidan

**Comment by mikepoz59** [comment]
My visual studio is set to use spaces because that's what we use at work, I'll switch and see if I can fix whatever appears as if it's massively changed.

Regarding passing a reference of the main form to a child window, I did that because of what I read on MSDN, specifically this page:  http://msdn.microsoft.com/en-us/library/bb383855(v=VS.90).aspx

But I'll figure out how to change so that I'm not passing a reference to main form to a child window.

-> And the method of putting the test case ID in the combo and then loading is way hacky.

I was trying to find a quick way to make use of the code you used without re-inventing the wheel and I figured this was the simplest way to do it.  I'll find another method to accomplish the same thing.

-> 4.Name of Query Picker class and file should be QueryPicker, not SelectQuery -- class names should be nouns, not verbs. Likewise for Test Case Picker.

I actually had that and then thought back to code reviews at work where they wanted the opposite. Six of one, half dozen of the other.  That said, it's your tool, I'll change it.

->  I got an email from my bug reporter from a crash that I assume happened while you were testing

This was actually because of the thing I explained before about clicking test cases too quickly which caused the tool to have a problem because of the background thread.

Regarding the placing of the other window, I understand what you're saying, I'll see if I can find a reasonable solution to that.

I'll see what I can do to resolve the concerns you have, and thanks for the speedy reply.

**Comment by ajryan** [comment]
(Edited after noticing that GitHub didn't parse the email correctly)

Hi Mike,

Looking at the diffs on your changes before you commit them is a good
practice, it helps you catch issues like spaces/tabs, among others.

On that MSDN page, you'll note that even in the comments below, someone
noted that the example is a poor design practice.

Classes are things, and their names should be nouns. Your colleagues who
want to name a class with a verb must have missed their V8!

Just want to reiterate that I can't accept anything that can crash if the
user doesn't "time something right." The reason for that crash is because
the picker knows too much about mainform and is reaching in to trigger what
is normally only run in response to an event. If you fire events from the
picker to the mainform, the synchronization worries should go away.

I'm excited to get this integrated, thanks for having the patience to work
with me on getting it right.

**Comment by mikepoz59** [comment]
Hi Ryan,

I got your gmail address from your github account page.  I figured I’d try adding that to the CC: line just in case the reply address doesn’t work and I can’t, for the life of me, find a way to send a message within GitHub.  Sorry for about that, GitHub is like a foreign language to me and I’m really stuck here.

Basically I tried to follow your directions and retract (close) the pull request and do the updates then resubmit but when I tried to sync the updates to GitHub, it basically blew up on me.  I’ve been struggling to get the code back to a state where it compiles and works (finally got it there) then tried again and it blew up again.

I seriously don’t understand what’s wrong, fortunately it didn’t screw up the project this time, and it LOOKS like the changes made it up but this isn’t like any source code manager I’ve ever used before (I’ve used SD with Microsoft, TFS, SVN, etc.) but GitHub is really making me wonder what kind of drugs the creator of this thing was on... <sigh>

Yeah, I know.

Anyway, if the changes I committed made it up there, I’m guessing you should be able to see them, if you cannot, please let me know what I need to do to make it visible to you, and any pointers to “github for dummies” would be greatly appreciated.

Thanks!
Mike Posluszny

**Pull request closed without merging**
